/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the files COPYING and Copyright.html.  COPYING can be found at the root   *
 * of the source code distribution tree; Copyright.html can be found at the  *
 * root level of an installed copy of the electronic HDF5 document set and   *
 * is linked from the top-level documents page.  It can also be found at     *
 * http://hdfgroup.org/HDF5/doc/Copyright.html.  If you do not have          *
 * access to either file, you may request a copy from help@hdfgroup.org.     *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Jan  3, 2018
 *			DA42327_CA <da42327_ca@c02sggw4g8wp.roswellpark.org>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"	    SUMMARY OF THE HDF5 CONFIGURATION\n"
	"	    =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"		   HDF5 Version: 1.8.7\n"
	"		  Configured on: Wed Jan  3 11:29:13 EST 2018\n"
	"		  Configured by: da42327_ca@c02sggw4g8wp.roswellpark.org\n"
	"		 Configure mode: production\n"
	"		    Host system: i386-apple-darwin15.6.0\n"
	"	      Uname information: Darwin c02sggw4g8wp.roswellpark.org 15.6.0 Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64 x86_64\n"
	"		       Byte sex: little-endian\n"
	"		      Libraries: \n"
	"	     Installation point: /Users/da42327_ca/devel/rhdf5/src/hdf5/hdf5\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"               Compilation Mode: production\n"
	"                     C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang\n"
	"                         CFLAGS: -Wall -Wextra -pedantic -O0 -ggdb\n"
	"                      H5_CFLAGS:  -w \n"
	"                      AM_CFLAGS: \n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API\n"
	"                    AM_CPPFLAGS: \n"
	"               Shared C Library: no\n"
	"               Static C Library: yes\n"
	"  Statically Linked Executables: no\n"
	"                        LDFLAGS: \n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	" 	 	Extra libraries:  -lz -lm \n"
	" 		       Archiver: ar\n"
	" 		 	 Ranlib: ranlib\n"
	" 	      Debugged Packages: \n"
	"		    API Tracing: no\n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                        Fortran: no\n"
	"\n"
	"                            C++: no\n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: no\n"
	"             High Level library: yes\n"
	"                   Threadsafety: no\n"
	"            Default API Mapping: v18\n"
	" With Deprecated Public Symbols: yes\n"
	"         I/O filters (external): deflate(zlib)\n"
	"         I/O filters (internal): shuffle,fletcher32,nbit,scaleoffset\n"
	"                            MPE: no\n"
	"                     Direct VFD: no\n"
	"                        dmalloc: no\n"
	"Clear file buffers before write: yes\n"
	"           Using memory checker: no\n"
	"         Function Stack Tracing: no\n"
	"                           GPFS: no\n"
	"      Strict File Format Checks: no\n"
	"   Optimization Instrumentation: no\n"
	"       Large File Support (LFS): yes\n"
	"             H5dump Packed Bits: yes\n"
;

