name: test build deploy

on:
  push:
    branches:
      - main
      - h5s_unlimited
  workflow_dispatch:

jobs:
  install-depdendencies:
    name: Install package dependencies
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-
            
      # - name: Install pkgs
      #   uses: docker://ghcr.io/grimbough/bioc-tinytex:3.16
      #   with:
      #     entrypoint: Rscript
      #     args: "-e 'library(remotes)' -e 'dev_package_deps(\'rhdf5\', dependencies = TRUE) |> update(upgrade = \'always\')'"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GRCH_TOKEN }}
      
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: bioconductor/bioconductor:devel-arm64
          options: |
            --platform linux/arm64 
            -v ${{ runner.temp }}/R-lib:/R-lib
          run: |
            uname -a
            export R_LIBS_USER=/R-lib
            Rscript -e 'library(remotes)' -e 'dev_package_deps(\'rhdf5\', dependencies = TRUE) |> update(upgrade = \'always\')'
      
 
      - name: Install pkgs
        run:
         docker run --platform linux/arm64 --entrypoint Rscript ghcr.io/grimbough/bioc-with-tinytex:3.16 -e 'library(remotes)' -e 'dev_package_deps("rhdf5", dependencies = TRUE) |> update(upgrade = "always")'
  
  check-arm64:
    name: Test package on ARM64
    runs-on: ubuntu-22.04

    steps:
    
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Clone package to be tested
        run: git clone https://git.bioconductor.org/packages/BiocStyle
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R-lib

      - name: Install Dependencies
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          install: |
            mkdir -p /build /tmp/R-lib
            echo "options(Ncpus=2L, timeout = 300)" >> ~/.Rprofile

          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
            
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
            
          run: |
            uname -m
            env
            Rscript -e "library(remotes)" -e "dev_package_deps(Sys.getenv('PKG'), dependencies = TRUE) |> update(upgrade = 'always')"
            
      - name: Install Package
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
          
          run: |  
            Rscript -e "options('Ncpus')"
            R CMD INSTALL ${PKG} &> ${PKG}.install-out.txt
            cat ${PKG}.install-out.txt
            
      - name: Build & Check Package
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: --platform=linux/arm64 bioconductor/bioconductor_docker:RELEASE_3_16
          githubToken: ${{ secrets.GHCR_TOKEN }}
          
          install: |
            Rscript -e "install.packages('tinytex')" \
              -e "tinytex::install_tinytex(extra_packages = c(
                'bera', 'caption', 'changepage', 'enumitem', 'fancyhdr', 
                'footmisc', 'marginfix', 'mathtools', 'nowidow', 'parnotes', 
                'parskip', 'placeins', 'ragged2e', 'soul', 'titlesec', 'xstring',
                'preprint', 'courier'
              ))"

          dockerRunArgs: |
            --volume "${PWD}:/build"
            --volume "${RUNNER_TEMP}/R-lib:/tmp/R-lib"
          env: |
            R_LIBS_USER: /tmp/R-lib
            PKG: /build/rhdf5
          
          run: |
            ## pdflatex isn't on the PATH unless we set this
            PATH=~/bin/:${PATH}
            R CMD build --keep-empty-dirs --no-resave-data ${PKG}
            R CMD check --install=check:${PKG}.install-out.txt --library="${R_LIBS_USER}" --no-vignettes --timings ${PKG}*.tar.gz
            mkdir -p ${PKG}.buildbin-libdir
            R CMD INSTALL --build --library=${PKG}.buildbin-libdir ${PKG}*.tar.gz
            
      - name: What's here?
        run: |
          echo "$PWD"
          ls -lh ${PWD}
          echo "${{ runner.temp }}/R-lib"
          ls -l ${{ runner.temp }}/R-lib
            
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: |
            ${GITHUB_WORKSPACE}/*.tar.gz
            ${GITHUB_WORKSPACE}/*.install-out.txt
            ${GITHUB_WORKSPACE}/*.Rcheck
          if-no-files-found: warn
  
