name: test build deploy

on:
  push:
    branches:
      - main
      - h5s_unlimited
  workflow_dispatch:
  
env:
  PKG: 'rhdf5'

jobs:
  install-depdendencies:
    name: Install package dependencies
    runs-on: ubuntu-22.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-
            
      # - name: Install pkgs
      #   uses: docker://ghcr.io/grimbough/bioc-tinytex:3.16
      #   with:
      #     entrypoint: Rscript
      #     args: "-e 'library(remotes)' -e 'dev_package_deps(\'rhdf5\', dependencies = TRUE) |> update(upgrade = \'always\')'"
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GRCH_TOKEN }}
      
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            -v ${{ runner.temp }}/R-lib:/R-lib
            -v ${{ github.workspace }}/../:/build
            --env R_USER_LIB=/R-lib
            --env PKG=${{ env.PKG }}
          run: |
            uname -a
            ls -l /build
            export R_LIBS_USER=/R-lib
            echo "options(Ncpus=2L, timeout = 300)" >> ~/.Rprofile
            Rscript -e "library(remotes)" -e "dev_package_deps('/build/${PKG}', dependencies = TRUE) |> update(upgrade = 'always')"
            
  check-arm64:
    name: Test package on ARM64
    runs-on: ubuntu-22.04
    needs:   install-depdendencies
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-
          
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            -v ${{ runner.temp }}/R-lib:/R-lib
            -v ${{ github.workspace }}/../:/build
            --env R_USER_LIB=/R-lib
            --env PKG=${{ env.PKG }}
            --workdir /build
          run: |
            R CMD build --keep-empty-dirs --no-resave-data ${PKG}

      - name: R CMD check
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            -v ${{ runner.temp }}/R-lib:/R-lib
            -v ${{ github.workspace }}/../:/build
            --env R_USER_LIB=/R-lib
            --env PKG=${{ env.PKG }}
            --workdir /build
          run: |
            R CMD check --install=check:${PKG}.install-out.txt --library="${R_LIBS_USER}" --no-vignettes --timings ${PKG}*.tar.gz
            cat ${PKG}.install-out.txt

      - name: R CMD INSTALL --build
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/grimbough/bioc-with-tinytex:devel-arm64
          options: |
            --platform linux/arm64
            -v ${{ runner.temp }}/R-lib:/R-lib
            -v ${{ github.workspace }}/../:/build
            --env R_USER_LIB=/R-lib
            --env PKG=${{ env.PKG }}
            --workdir /build
          run: |
            mkdir -p ${PKG}.buildbin-libdir
            R CMD INSTALL --build --library=${PKG}.buildbin-libdir ${PKG}*.tar.gz
            
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: |
            ${{ github.workspace }}/*.tar.gz
            ${{ github.workspace }}/*.install-out.txt
            ${{ github.workspace }}/*.Rcheck
          if-no-files-found: warn
          


  
