on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 2, cache: 1}
        - { os: macOS-latest,   bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 3, cache: 1}
        - { os: macos-15-intel, bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 3, cache: 2}
        - { os: ubuntu-latest,  bioc-version: 'devel', bioc-mirror: 'https://bioconductor.posit.co/',  Ncpus: 4, cache: 1}
        - { os: ubuntu-latest,  bioc-version: 'release',  bioc-mirror: 'https://packagemanager.posit.co/bioconductor',  Ncpus: 4, cache: 1}
    steps:
      - uses: actions/checkout@v6

      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: ${{ matrix.config.bioc-mirror }}

      - name: Install openssl
        if: runner.os == 'macOS'
        run: |
          sudo R -e 'source("https://mac.R-project.org/bin/install.R")' -e 'install.libs("openssl")'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # We use cache versioning to differentiate between Intel and ARM macOS builds
          # https://github.com/r-lib/actions/issues/1035
          cache-version: ${{ matrix.config.cache }}
          extra-packages: |
            rcmdcheck

      - name: Bioc - Build, Install, Check
        uses: grimbough/bioc-actions/build-install-check@v1

      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 
