name: Test R-universe

on:
  workflow_dispatch:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

permissions:
  contents: read

jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: bioc
      organization: bioconductor
